export default {
  login: "saikatbhuiyan",
  id: 44515748,
  node_id: "MDQ6VXNlcjQ0NTE1NzQ4",
  avatar_url: "https://avatars.githubusercontent.com/u/44515748?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/saikatbhuiyan",
  html_url: "https://github.com/saikatbhuiyan",
  followers_url: "https://api.github.com/users/saikatbhuiyan/followers",
  following_url:
    "https://api.github.com/users/saikatbhuiyan/following{/other_user}",
  gists_url: "https://api.github.com/users/saikatbhuiyan/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/saikatbhuiyan/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/saikatbhuiyan/subscriptions",
  organizations_url: "https://api.github.com/users/saikatbhuiyan/orgs",
  repos_url: "https://api.github.com/users/saikatbhuiyan/repos",
  events_url: "https://api.github.com/users/saikatbhuiyan/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/saikatbhuiyan/received_events",
  type: "User",
  site_admin: false,
  name: "Md. Shahabuddin Bhuiyan",
  company: null,
  blog: "",
  location: "Dhaka, Bangladesh",
  email: null,
  hireable: true,
  bio: "Python || Django || Flask || FastAPI || JavaScript || Vue || Node || React ",
  twitter_username: null,
  public_repos: 134,
  public_gists: 0,
  followers: 17,
  following: 15,
  created_at: "2018-10-27T02:48:18Z",
  updated_at: "2022-08-28T12:17:35Z",
};
